"""Perguntas práticas do Caderno Local, agrupadas para busca e navegação."""
HELP_GROUPS = [
    {"title": "Começar e cuidar dos seus dados", "description": "Instalação, acesso local e cópias de segurança.", "items": [
        ("Como começo a usar o Caderno Local?", "Instale as dependências indicadas no README, execute app.py e abra o endereço local mostrado no terminal. Importe a primeira planilha na área Importar questões."),
        ("Preciso criar uma conta?", "Não. O aplicativo roda no seu computador e não exige cadastro."),
        ("Preciso de internet para estudar?", "Não para usar as funções do aplicativo e seus arquivos locais. Uma IA externa, caso você a escolha para preparar a planilha, pode precisar de internet."),
        ("Onde ficam as questões e as respostas?", "No banco SQLite dentro da pasta instance/. As provas em PDF usadas para figuras ficam em static/provas/."),
        ("Como faço backup do meu estudo?", "Feche o aplicativo e copie a pasta instance/ inteira. Se usou PDFs ou imagens das provas, copie também static/provas/ e static/imagens/. Guarde as planilhas originais."),
        ("Troquei de computador. Como levo meus dados?", "Copie instance/ e seus PDFs/imagens para as mesmas pastas da instalação nova, com o aplicativo fechado. Abra o programa e confira a visão geral."),
        ("Posso apagar o banco SQLite para começar do zero?", "Isso apaga questões, sessões, tentativas e cartões. Faça uma cópia de instance/ antes de substituir ou remover arquivos."),
    ]},
    {"title": "Planilha e importação", "description": "Modelo, colunas, duplicatas e erros de validação.", "items": [
        ("Onde baixo a planilha modelo?", "Use o botão Baixar planilha modelo na página Importar questões. A aba de dados deve continuar com o nome Questoes."),
        ("Posso enviar PDF direto ao importador?", "O importador recebe uma planilha .xlsx. Para transformar prova e gabarito em planilha, use o prompt copiável da mesma página com a IA que preferir."),
        ("Quais arquivos devo enviar à IA?", "Envie a planilha modelo vazia, o PDF da prova da versão correta, o gabarito definitivo e o texto do prompt da página Importar questões."),
        ("A IA só me entregou CSV ou texto. Como importo?", "Peça os dados em TSV com os 23 cabeçalhos na ordem do modelo; cole as linhas na aba Questoes e salve uma cópia .xlsx. Confira se nenhuma coluna deslocou."),
        ("O que significa importação cancelada?", "A validação encontrou campos vazios ou inconsistências e não gravou nenhuma questão daquele arquivo. Corrija as linhas citadas na mensagem e envie novamente."),
        ("Se eu importar a mesma prova duas vezes, ela duplica?", "Não. Banca, concurso, cargo, ano, prova e número formam a identidade de cada questão; itens já cadastrados são ignorados."),
        ("Por que minha planilha importou menos questões que o total de linhas?", "Linhas vazias são ignoradas e questões com a mesma identificação já existente não são inseridas. Veja os totais exibidos após importar."),
    ]},
    {"title": "Gabaritos, formatos e classificação", "description": "Alternativas, anuladas, datas e assuntos.", "items": [
        ("Posso importar questões com apenas quatro alternativas?", "Sim. Para tipo AE, preencha A, B, C e D; deixe E em branco quando a prova não tiver quinta alternativa."),
        ("Como registro uma questão de Certo ou Errado?", "Use tipo CE, alternativa_c=Certo e alternativa_e=Errado. Deixe A, B e D vazias e use C ou E no gabarito."),
        ("Como marco uma questão anulada?", "Escreva ANULADA em gabarito e em situacao. Ela fica no banco como registro, mas não entra nas sessões de estudo."),
        ("Devo usar gabarito preliminar ou definitivo?", "Prefira o definitivo, já considerando alterações e anulações. Confira se ele corresponde à versão/caderno da prova."),
        ("O que faço se não encontro o gabarito?", "Separe a questão para conferência antes da importação. O sistema precisa de gabarito válido para corrigir tentativas; evite inventar uma letra."),
        ("Como preencher a data da prova?", "Use DD/MM/AAAA ou AAAA-MM-DD. Se não souber a data exata, deixe data_prova em branco e mantenha o ano correto."),
        ("Os assuntos micro são classificados automaticamente?", "Há classificação auxiliar para rótulos genéricos, mas ela pode errar. Inclua na planilha macro e micro úteis e confira os rótulos após importar."),
    ]},
    {"title": "Figuras e PDFs", "description": "Páginas originais, referências visuais e arquivos locais.", "items": [
        ("Como faço as figuras aparecerem junto das questões?", "Copie o PDF original para static/provas/ e registre arquivo_pdf como provas/nome-do-arquivo.pdf, além do número correto em pagina. O aplicativo gera imagens locais das páginas quando necessário."),
        ("Qual número devo escrever em pagina?", "Conte as páginas do arquivo PDF começando na primeira página como 1, inclusive capa. Não use a numeração impressa se ela não corresponder à posição no arquivo."),
        ("A figura abre automaticamente em todas as questões?", "A visualização é aberta quando o enunciado indica figura ou elemento visual. Nas demais, você pode abrir a página original manualmente."),
        ("O PDF precisa ficar na mesma pasta da planilha?", "Não. Os PDFs usados para figuras devem ser copiados para static/provas/; na planilha, informe somente o caminho relativo começando com provas/."),
        ("Posso usar uma imagem recortada em vez do PDF inteiro?", "Sim. Coloque a imagem em static/imagens/ e preencha imagem com um caminho relativo como imagens/figura.png."),
        ("Por que a imagem de uma questão não aparece?", "Confira se arquivo_pdf ou imagem coincide exatamente com o nome do arquivo, inclusive extensão, e se pagina indica uma página existente do PDF."),
        ("O aplicativo faz OCR de PDFs escaneados?", "A conversão de prova escaneada para texto deve ser feita antes da importação, pela ferramenta de OCR/IA escolhida. Compare símbolos, números e alternativas com as páginas originais."),
    ]},
    {"title": "Estudar e organizar sessões", "description": "Filtros, respostas, tempo, impressão e histórico.", "items": [
        ("Como escolho só uma matéria para estudar?", "Abra Estudar questões, selecione a matéria macro e depois o assunto micro, aplique os filtros e gere uma sessão."),
        ("O filtro micro muda quando escolho a macro?", "Sim. Ele apresenta os assuntos disponíveis para a macro escolhida no seu banco de questões."),
        ("Como estudar questões que nunca respondi?", "Selecione a opção de histórico para questões não vistas na área Estudar questões antes de gerar a sessão."),
        ("Posso parar uma sessão e voltar depois?", "Sim. Abra Histórico e clique na sessão para retomar as questões pendentes."),
        ("Quando o tempo de cada questão começa?", "Na sessão comum, o contador da questão começa quando a página dela é aberta."),
        ("Como imprimo uma sessão ou salvo um PDF?", "Na sessão, clique em Imprimir esta sessão / salvar PDF e use a janela de impressão do navegador para escolher impressora ou Salvar como PDF."),
        ("Posso renomear uma sessão depois de criada?", "Sim. Use o lápis do Histórico para dar um nome que facilite encontrá-la. Os filtros permitem buscar nome, assunto, situação e intervalo de datas."),
    ]},
    {"title": "Simulados", "description": "Montagem proporcional, repetição e resultado final.", "items": [
        ("Como monto um simulado?", "Abra Simulados, escolha o concurso, indique a quantidade de questões e, se desejar, filtre a banca. O sistema mostra a distribuição de referência antes de começar."),
        ("Tenho que escolher uma banca?", "Não. Sem banca, o simulado pode combinar as bancas existentes para o concurso selecionado."),
        ("O simulado corrige cada resposta imediatamente?", "Não. Gabarito e correção aparecem somente quando todas as questões do simulado foram respondidas."),
        ("Existe limite de tempo para encerrar o simulado?", "Não há encerramento automático por tempo. O tempo total é contabilizado enquanto você realiza a prova."),
        ("Por que apareceram questões repetidas?", "Questões inéditas têm prioridade, mas o simulado pode repetir itens, inclusive aqueles errados ou marcados com dúvida, para preservar os assuntos recorrentes."),
        ("Como são distribuídas as matérias no simulado?", "O programa usa a composição das provas do concurso presentes no acervo como referência, com possibilidade de incluir temas menos frequentes."),
        ("Posso imprimir um simulado antes de terminá-lo?", "Sim, é possível imprimir as questões. O gabarito continua oculto até o fim do simulado."),
    ]},
    {"title": "Revisão e desempenho", "description": "Erros, cartões e interpretação dos gráficos.", "items": [
        ("Quais questões entram em Revisão?", "Itens que você errou, respondeu com dúvida ou marcou manualmente para revisar."),
        ("Como encontro questões parecidas com uma que errei?", "Na Revisão, use o comando de questões semelhantes para montar uma sessão com itens relacionados ao assunto."),
        ("Posso fazer meus próprios flashcards?", "Sim. Na Revisão você pode escrever frente e verso, responder os cartões e acompanhar os que estão para revisar."),
        ("A porcentagem de acerto inclui revisões?", "Sim. Os indicadores de desempenho consideram as tentativas registradas, incluindo revisões."),
        ("O que significam questões distintas e tentativas?", "Questões distintas conta cada item respondido ao menos uma vez; tentativas conta todas as respostas, inclusive repetições."),
        ("Como vejo minha evolução em um período?", "Em Desempenho, use os filtros de período. Os gráficos mostram atividade e porcentagem de acertos, com média ou tendência e a meta de 80%."),
        ("Posso comparar concursos, anos e bancas?", "Sim. Nos filtros do painel de Desempenho, selecione concurso, ano e banca para comparar a composição do acervo."),
    ]},
    {"title": "Problemas comuns e limites", "description": "Erros frequentes e decisões importantes antes de compartilhar.", "items": [
        ("O site mostra zero questões depois de uma atualização. Por quê?", "O banco de questões fica na pasta instance/ da instalação que o programa está usando. Confirme que você copiou a pasta correta para a versão em execução e reinicie o aplicativo."),
        ("Por que uma alternativa E vazia aparece na sessão?", "Nas versões atuais, questões AE com apenas A-D exibem somente as alternativas preenchidas. Atualize para esta versão se ainda vir uma E vazia."),
        ("Posso importar questões sem banca ou fonte?", "Não. São campos exigidos pelo importador para permitir identificação e conferência da origem."),
        ("Por que o aplicativo rejeitou um caminho de PDF?", "Use apenas caminho relativo começando com provas/ e terminando em .pdf, sem diretórios superiores ou URL."),
        ("Por que não aparecem matérias no gráfico de rosca?", "A distribuição usa questões importadas e muda com concurso, ano e banca selecionados. Confira se há itens para os filtros escolhidos."),
        ("O Caderno Local gera questões inéditas com IA?", "Não nesta versão. Os simulados são montados a partir das questões que você importou; nenhuma questão nova é inventada."),
        ("Posso publicar minhas provas e o banco pessoal no GitHub junto do código?", "Evite incluir instance/, PDFs de terceiros, imagens extraídas e planilhas pessoais no repositório público. Publique apenas o código e o modelo vazio, respeitando os direitos sobre as provas."),
    ]},
]
